#!/bin/bash
set -Eeuo pipefail

notify(){
    value=$1
    message_icon=$2
    msgId=$3
    filled_icon=$4
    not_filled_icon=$5

    user_title=${6:-}

    volume_percentage="$(\
        ~/.config/dunst/notify-percent-process-string \
        10 "$filled_icon " "$not_filled_icon " "$value" \
        )"

    messages[0]="$value"
    messages[1]=$volume_percentage

    message_title=${user_title:-${messages[0]:-}}

    dunstify \
        -a "changeVolume" \
        -u low \
        -i audio-volume-muted \
        -r "$msgId" \
        -t 2000 \
        "$message_icon: $message_title" \
        "${messages[1]:-}"
    }

while getopts ":t:vb" opt; do
    case $opt in
        t) title="$OPTARG" ;;
        v)
            volume="$(pamixer --get-volume-human || true)"
            message_icon="🔊"
            msgId="9991048"
            filled_icon="🔴"
            not_filled_icon="⭕"
            RUN="notify ${volume%\%*} $message_icon $msgId $filled_icon $not_filled_icon"
            ;;
        b)
            bright="$(light)"
            bright="${bright%.*}"
            message_icon="🔆"
            msgId="9991049"
            filled_icon="🌞"
            not_filled_icon="🌑"
            RUN="notify ${bright%.*} $message_icon $msgId $filled_icon $not_filled_icon"
            ;;
        :)
            echo "No argument provided for option (-$OPTARG)"
            ;;
        \?)
            echo "Invalid option (-$OPTARG)"
            ;;
    esac
done
shift $((OPTIND - 1))

eval "$RUN \"${title:-}\""
