#!/bin/bash
# vim: ft=zsh:ts=4:sw=4
# shellcheck disable=2142

###############
#             #
# Git Aliases #
#             #
###############

# Utils
# =====
alias gb='git branch -a'
alias gs='clear && git status 2> /dev/null'
alias gl='f(){git log --grep="$1"};f'
alias co='git checkout'
alias gclean='git clean -df'
alias lsgst='git stash list'
alias gr='git remote'
alias grl='git reflog'
alias gst='git stash'
alias grs='git reset'
alias uptrefs='git fetch origin --prune'

# Fetch
# =====
alias gf='git fetch -v'
alias gfup='git fetch upstream'

# Add
# ===
alias ga='git add'
alias gall='git add -A && gs'
alias gau='git add -u'

# Diff
# ====
alias gd='clear && git diff'
alias gds='clear && git diff --staged'
alias gdt='git difftool'
alias gdm='git diff remotes/origin/master..'
alias gdms='git diff --stat --color master..'

# Pull/Push
# =========
alias gp='git fetch && git pull'
alias gpsm='git push origin master'

# Merge
# =====
alias gmt='git mergetool'
alias gma='git merge --abort'

# Rebase
# ======
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbm='git rebase master'
alias grbc='git rebase --continue'

# Commit
# ======
alias gcz='gcm z'
alias gcma='gcm a'
alias gcman='gcm n'

# Release
alias grls='npx semantic-release'

#################
#               #
# Other Aliases #
#               #
#################

# LS'
# ====
alias lsgem='gem list'
alias lsnvm='nvm list'
alias lspip='pip3 list'
alias lsnpm='npm ls --depth 0'
alias lspath='for I in $(tr : " " <<<$PATH);do echo $I; done'
alias lsfonts='fc-list'

# NVM
# ===
alias nvmv='nvm current'
alias nvmd='nvm alias default '

# NPM
# ===
alias npmprune='npm prune && npm i && npm i'
alias rstnpm='clear && rm -rf ./node_modules && npm i && npm i'
alias rnpm='npm remove'

# cds
# ===
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias cdssh='cd ${HOME}/.ssh && ls'
alias cdvagrant='cd /vagrant/'

# Docker
# ======
alias dk='docker'
alias dkc='docker-compose'
alias dki='docker images -a'
alias dkps='docker ps'
alias dkrit='docker run -it'
alias dkeit='docker exec -it'
alias dkinfo='clear && dki && echo -e "\n\n#######################\n\n" && dkps -a'

# Elm
# ===
alias em='elm make'
alias er='elm repl'
alias epi='elm package install'

# tmux
# ====
alias tmuxinstall="~/.tmux/plugins/tpm/bin/install_plugins"
alias tmuxupdate="~/.tmux/plugins/tpm/bin/update_plugins"
alias tmuxclean="~/.tmux/plugins/tpm/bin/clean_plugins"
alias tm='tmux'
alias tma='tmux attach'

##########
#        #
# Random #
#        #
##########

alias xx='exit'
alias bgdisown='bg && disown'
alias poweroff='shutdown -P now'
alias susu='sudo su'
alias del='rm -rf'
alias clr='clear && '
alias cpp='rsync -aP '
alias v='nvim'
alias less='less -R'
alias doge-quotes='while true; do doge | lolcat -a -d 100 -s 100 -p 1; done'
alias testunicode='curl -sL http://www.cl.cam.ac.uk/\~mgk25/ucs/examples/UTF-8-demo.txt'
alias tp='command -v'
alias xcat='xargs cat'
alias trackpadgesture='libinput-gestures-setup'
alias termitereload='killall -USR1 termite'
alias btc='bluetoothctl'
