#!/bin/bash
# vim: ft=zsh:ts=4:sw=4
# shellcheck disable=1090

addToPath(){
    local ITEM
    for ITEM in "$@"; do
        PATH="$ITEM:$PATH"
    done
}

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# bin
addToPath ~/.bin
addToPath ~/.local/bin
addToPath ~/.scripts

# yarn
addToPath ~/.yarn/bin
addToPath ~/.config/yarn/global/node_modules/.bin

# golang
addToPath ~/{.,}go/bin

# rust
addToPath ~/.cargo/bin

########################
#                      #
# This need to go last #
#                      #
########################

# Load RVM into a shell session *as a function*
[[ -s ~/.rvm/scripts/rvm ]] && . ~/.rvm/scripts/rvm
