#!/bin/bash
# vim: ft=zsh:ts=4:sw=4
# shellcheck disable=1090

addToPath(){
    local ITEM
    for ITEM in "$@"; do
        PATH="$ITEM:$PATH"
    done
}

# homebrew
addToPath /opt/homebrew/bin

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# bin
addToPath ~/.bin
addToPath ~/.local/bin
addToPath ~/.scripts

# yarn
addToPath ~/.yarn/bin
addToPath ~/.config/yarn/global/node_modules/.bin

# golang
addToPath ~/{.,}go/bin

# rust
addToPath ~/.cargo/bin

# dotnet
addToPath ~/.dotnet

# pyenv
addToPath $(pyenv root)/shims

# php@7.4
addToPath /usr/local/opt/php@8.1/bin
addToPath /usr/local/opt/php@8.1/sbin

# vscode
addToPath /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/

# bun
addToPath ~/.bun/bin

########################
#                      #
# This need to go last #
#                      #
########################

# ruby (homebrew)
addToPath /usr/local/opt/ruby/bin
addToPath /usr/local/lib/ruby/gems/3.0.0/bin
export LDFLAGS="-L/usr/local/opt/ruby/lib"
export CPPFLAGS="-I/usr/local/opt/ruby/include"
export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"

# Load RVM into a shell session *as a function*
[[ -s ~/.rvm/scripts/rvm ]] && . ~/.rvm/scripts/rvm
