#!/bin/bash
# vim: ft=zsh:ts=4:sw=4
# shellcheck disable=2142

# Uses fzf to search for files and open then with your default editor
# ===================================================================
function __edit_file_widget {
    local FILES
    FILES="$(__fsel)"
    if [ -z "$FILES" ]
    then
        zle reset-prompt
        return 1
    fi
    eval "$EDITOR $FILES"
    zle reset-prompt
}
zle -N __edit_file_widget
bindkey -M viins '^E' __edit_file_widget

# map 'C-z' to 'fg' command, this would allow you to toggle
# between your current program and the terminal
# =========================
__foreground_job(){
    fg 2> /dev/null
    zle reset-prompt
}
zle -N __foreground_job
bindkey -M viins '^Z' __foreground_job

# edit commandline
bindkey -M viins '^X^E' edit-command-line
