# vim: ft=zsh:ts=4:sw=4

export EDITOR=nvim

# Setting fd as the default source for fzf
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow -g !.git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# OH MY ZSH
export DISABLE_AUTO_TITLE="true"

# Spaceship PROMPT
export SPACESHIP_VI_MODE_SHOW=false
export SPACESHIP_USER_SHOW=false
export SPACESHIP_HOST_SHOW=false
export SPACESHIP_GIT_BRANCH_COLOR="green"
export SPACESHIP_CHAR_SYMBOL="↪ "
export SPACESHIP_JOBS_SYMBOL="♦"

# TMUX
export ZSH_TMUX_AUTOSTART=true

# GPG
export GPG_TTY=$(tty)

# GoLang
export GOROOT="$HOME/.go"
export GOPATH="$HOME/go"

export OS=$(getos 2> /dev/null)

