#!/bin/bash

case "$1" in
    h|l) SPLIT="h" ;;
    j|k) SPLIT="v" ;;
    *)   SPLIT="v"
esac

if [[ $1 =~ ^[hjkl]$ ]]; then
    shift
fi

FILE_PATH=${1:-.}

FILE_PATH_ABS=$(
    cd "$FILE_PATH" || exit
    pwd
)

tmux split-window -"$SPLIT" -c "$FILE_PATH_ABS"
clear
