#!/bin/bash -e

# This `add`, `commit --amend` and `git push -f --no-verify`
# all the changes in the current branch to its remote one

CURRENT_BBRANCH=$(git symbolic-ref --short -q HEAD)

validate_master(){
    if [ "$BYPASS" ]
    then
        return 0
    fi
    if [ "$CURRENT_BBRANCH" = "master" ]
    then
        echo "¯\\_(ツ)_/¯"
        echo "You're on master, sorry bruh..."
        echo "Use (-f) if you want to bypass the security measures ;)"
        return 1
    fi
}

# Parse options
while getopts ":f" OPT
do
  case $OPT in
      f) BYPASS=true ;;
      *)
          echo "Bad option (-$OPTARG)"
          exit 1
          ;;
  esac
done
shift $((OPTIND - 1))

validate_master

git add -A
git commit --amend --no-edit --no-verify
git push origin "$CURRENT_BBRANCH" -f

