#!/bin/bash

# Deletes all docker containers and images

MESSAGE="
Are you sure that you want to delete all docker
images/containers hard? Really, reaaally hard ? ( ͡° ͜ʖ ͡°) [y, n]: \
"

read -rsn1 -p "$MESSAGE" IS_HARD
echo

[ "$IS_HARD" != "y" ] && exit 1

docker rm "$(docker ps -aq)" -f
docker rmi "$(docker images -q)" -f
