#!/bin/bash

__message(){
  echo ":: Script \`$1\` created ::"
}

__scriptify(){
  echo -e "#!/bin/bash\n\n${BODY:-"echo \"Hello World\""}\n" > $1

  chmod u+x $1

  __message $1
}

# Parse options
while getopts ":b:" OPT
do
  case $OPT in
    "") BODY=$OPTARG ;;
  esac
done
shift $((OPTIND - 1))

[ $# -lt 1 ] && {
  __scriptify script.sh $BODY
  exit 0
}

# Begin
# =====
for SCRIPT in $@
do
  __scriptify $SCRIPT $BODY
done

