#!/bin/bash
set -Eeuo pipefail

FILES_CREATED=()

# {{{ Script templates
BASH_TEMPLATE=$(
cat <<EOF
#!/bin/bash
set -Eeuo pipefail
EOF
)

NODE_TEMPLATE=$(
cat <<EOF
#!/usr/bin/env node
EOF
)
# }}}

make_script(){
    local script_name template
    script_name=$1
    template=${2:-$BASH_TEMPLATE}

    echo "$template" > "$script_name"

    chmod u+x "$script_name"
    echo ":: Script \`$script_name\` created ::"
}

main(){
    local script opt

    while getopts ":b:n:" opt; do
        FILES_CREATED+=("$OPTARG")

        case $opt in
            b)
                make_script "$OPTARG" "$BASH_TEMPLATE"
                ;;
            n)
                make_script "$OPTARG" "$NODE_TEMPLATE"
                ;;
            *)
                echo "Option (-$opt) is not valid..."
                exit 1
                ;;
        esac
    done
    shift $((OPTIND - 1))

    for script in "$@"; do
        FILES_CREATED+=("$script")

        make_script "$script" "$BASH_TEMPLATE"
    done
}

main "$@"

eval "$EDITOR -c'norm G' ${FILES_CREATED[*]}"
