#!/bin/bash -e

# Execute given commands invinitely (Until canceled)
# with a interval of time between re-execution

# Parse options
while getopts ":t:" OPT
do
  case $OPT in
      t) TIME="$OPTARG" ;;
      *) TIME="1s"
  esac
done
shift $((OPTIND - 1))

while :
do
    eval "$@"
    sleep "${TIME:-1}"
done

