#!/bin/bash

# Shows a notification depending on what OS you are

SCRIPT_NAME='dsply'

__mac(){
    osascript -e "display notification \"${MESSAGE:-Hello}\" with title \"${TITLE:-Title}\" $SOUND"
}

__tmux(){
    tmux display "$MESSAGE"
}

# Parse options
while getopts ":bt:m:" OPT
do
  case $OPT in
      t) TITLE="$OPTARG" ;;
      m) MESSAGE="$OPTARG" ;;
      b) SOUND="sound name \"Submarine\"" ;;
      *) SOUND="" ;;
  esac
done
shift $((OPTIND - 1))

case "$(uname -s)" in
    [Dd]arwin)
        __mac
        ;;
    *)
        if [[ "$TMUX" ]]
        then
            __tmux
        else
            echo "\`$SCRIPT_NAME\` Cannot be used at this time ¯\\_(ツ)_/¯"
        fi
        ;;
esac

