#!/bin/bash
set -Eeuo pipefail

if command -v gpg &> /dev/null; then
    if gpg -K | grep 'cabaalexander' &> /dev/null && \
    [ "$(git config user.name)" == "cabaalexander" ]; then
        sighned="-S";
    fi
fi

base_command="git commit ${sighned:-}"

user_input="${1:-}"

case $user_input in
    a) git_command="$base_command --amend";;
    z) git_command="git cz ${sighned:-}";;
    n) git_command="$base_command --amend --no-edit --no-verify";;
    m) git_command="$base_command -m";;
    *)
        if [ -n "$user_input" ]; then
            echo "Option not available ($user_input)"
            exit 0
        fi
        ;;
esac

if [ $# -gt 0 ]; then
    shift
fi

eval "${git_command:-$base_command} $*"
