#!/bin/bash
set -Eeuo pipefail

if gpg -K | grep 'cabaalexander' &> /dev/null; then
    sighned="-S";
fi

base_command="git commit ${sighned:-}"

case ${1:-} in
    a) git_command="$base_command --amend";;
    z) git_command="npx git-cz ${sighned:-}";;
    n) git_command="$base_command --amend --no-edit --no-verify";;
esac

eval "${git_command:-$base_command}"
