#!/bin/bash
set -Eeuo pipefail

FIRST_PARAM=${1:-}
AHEAD=$(git rev-list --left-right --count origin/master.. | cut -f2)

if [ "$AHEAD" -eq 0 ]; then
    AHEAD=1
fi

clear
git log -p -"${FIRST_PARAM:-$AHEAD}"
