#!/bin/bash

# gdsf - git destroy file

PATH_TO_FILE=${1:?"Provide a file to destroy from history..."}

git filter-branch --force --index-filter \
"'git rm --cached --ignore-unmatch $PATH_TO_FILE'" \
--prune-empty --tag-name-filter cat -- --all

