#!/bin/bash
set -Eeuo pipefail

FIRST_PARAM=${1:-}
AHEAD=$(gahead)

if [ "$AHEAD" -eq 0 ]; then
    AHEAD=1
fi

clear
files=$(
    git log -p -"${FIRST_PARAM:-$AHEAD}" --name-status --oneline |
        awk '$1 ~ /^[a-zA-Z0-9]+$/ && $1 != "D" && NR != 1 {print $NF}' |
        tr '\n' ' '
)

eval "${EDITOR:-vim} $files"
