#!/bin/bash
set -Eeuo pipefail

# getip - gets your machine ip. It will try to use the commands `ip` or
# `ifconfig` to get you the ip. You only get print only one ip. (as expected)

ip_decoder(){
    grep 'UP' |
        awk '$3 ~ /\/24/ {sub(/\/[0-9]+/, ""); print $3}'
}

ipconfig_decoder(){
    grep 'broadcast' |
        head -1 |
        awk '{print $2}'
}

get_ip(){
    local CMD OPT DEC
    CMD=$1
    OPT=$2
    DEC=$3
    if command -v "$CMD" &> /dev/null; then
        eval "$CMD $OPT" | "$DEC" && return 0
    fi
    return 1
}

main(){
    local COMMAND OPTIONS DECODER
    IFS=$':'
    while read -rs COMMAND OPTIONS DECODER; do
        # if you get any valid IP you break and 'DA SET'
        get_ip "$COMMAND" "$OPTIONS" "$DECODER" && break
    done
}
main <<EOF
ip:-br addr show:ip_decoder
ifconfig::ipconfig_decoder
EOF
