#!/bin/bash

# Git pulls "hard" from a repo

CURRENT_BRANCH=$(gcb)

MESSAGE="This will perform a hard reset with the branch \
'origin/$CURRENT_BRANCH'."

echo -e $MESSAGE
read -rsn1 -p "Do you wish to continue ? [y, n]: " IS_HARD
echo

[ "$IS_HARD" != "y" ] && exit 1

echo "Fetching..."
git fetch origin "$CURRENT_BRANCH" &> /dev/null
git reset --hard "origin/$CURRENT_BRANCH"

