#!/bin/bash

while getopts ":b:r:" opt; do
    case $opt in
        b) branch="$OPTARG" ;;
        r) remote="$OPTARG" ;;
        :)
            echo "No argument provided for option (-$OPTARG)"
            ;;
        \?)
            echo "Invalid option (-$OPTARG)"
            ;;
    esac
done
shift $((OPTIND - 1))

# Git pulls "hard" from a repo

CURRENT_BRANCH=${branch:-$(gcb)}
ORIGIN=${remote:-origin}

MESSAGE="This will perform a hard reset with the branch \
'origin/$CURRENT_BRANCH'."

echo -e $MESSAGE
read -rsn1 -p "Do you wish to continue ? [y, n]: " IS_HARD
echo

[ "$IS_HARD" != "y" ] && exit 1

echo "Fetching..."
git fetch "$ORIGIN" "$CURRENT_BRANCH"
git reset --hard "$ORIGIN/$CURRENT_BRANCH"

