#!/bin/bash

# Git pulls "hard" from a repo

MESSAGE=$"\
Are you sure that you want to pull hard ? \
Really, reaaally hard ? ( ͡° ͜ʖ ͡°) [y, n]: \
"

read -rsn1 -p "$MESSAGE" IS_HARD
echo

[ "$IS_HARD" != "y" ] && exit 1

CURRENT_BRANCH=$(gcb)

echo "Fetching..."
git fetch origin "$CURRENT_BRANCH" &> /dev/null
git reset --hard "origin/$CURRENT_BRANCH"

