#!/bin/bash
set -Eeuo pipefail

# Squash all the commits ahead of master for the current branch

USER_INPUT="${1:-}"

if [ -n "$USER_INPUT" ]; then
    SQUASH="$USER_INPUT"
else
    SQUASH=$(git rev-list --left-right --count origin/$(gmain).. | cut -f2)
    test "$SQUASH" -lt 2 && exit 0
fi


git rebase -i HEAD~"$SQUASH"
