#!/bin/bash
set -Eeuo pipefail

# Squash all the commits ahead of master for the current branch

AHEAD=$(git rev-list --left-right --count origin/master.. | cut -f2)

test "$AHEAD" -lt 2 && exit 0

git rebase -i HEAD~"${1:-$AHEAD}"
