#!/bin/bash -e

GIT_COMMANDS=(
    "fetch -v"
    "branch temp 2> /dev/null || true"
    "checkout temp"
    "pull origin temp 2> /dev/null || true"
    "add ."
    "commit -m temp"
    "push origin temp"
    "checkout master"
)

IFS=$'\n'
for COMMAND in ${GIT_COMMANDS[*]}; do
    eval "git $COMMAND"
done
