#!/bin/bash

# Installs node.js packages and saves them automatically on its package.json

while getopts ":g" OPT
do
  case $OPT in
    g)
      FLAG="-g"
      ;;
    \?)
      echo "Invalid option (-$OPTARG)"
      ;;
  esac
done
shift $((OPTIND - 1))

[ $# -lt 1 ] && npm i $FLAG

npm i "$FLAG" "$@"

